---
protocol-key-pair: IgVTv2ATyexvnfKia6TzXbpa96I5tQOoW/brf/0OLVylDkg6aHDgUP9Y3VCKOckjkSFZGVOLcmSuAILCu4yuS9n/Y95u38H2r+c2oolKAvsOcZnccuAKZFcGDJs9eIiEU+i2YZZRPvbBOz5xQGyNSpJ5PpO82Aj5yOif1MA+YWU=
worker-key-pair: SU95dI18C1XZMTRvYADT72UmuvLIHg/onieMVy0SnF49ULo9Di+4EgUUCJUTyOwY3ivXLeXAyZGcsor8C6zyFw==
account-key-pair: ADwKov+mtFK3Hbv4YnFMKQ1FqXwjSmzyVf3K8QSad88dnSA6efptM0CypA7/gBsddrkqyTtyz3cMIcIUn3Hqovg=
network-key-pair: EDjvJ4ThH7Jx78hJcon59VHys8tiM3g4wmatu84qr/VtkrbQAumiCWIMDTAPsZG9ZzGds8CZl4StNgDBToIAmg==
db-path: /root/.sui/sui_config/authorities_db/a50e483a6870e050ff58dd508a39c92391215919538b7264ae0082c2bb8cae4bd9ff63de6edfc1f6afe736a2894a02fb0e7199dc72e00a6457060c9b3d78888453e8b66196513ef6c13b3e71406c8d4a92793e93bcd808f9c8e89fd4c03e6165
network-address: /ip4/0.0.0.0/tcp/41509/http
json-rpc-address: "0.0.0.0:41005"
metrics-address: "0.0.0.0:40517"
admin-interface-port: 35307
consensus-config:
  address: /ip4/0.0.0.0/tcp/33587/http
  db-path: /root/.sui/sui_config/consensus_db/a50e483a6870e050ff58dd508a39c92391215919538b7264ae0082c2bb8cae4bd9ff63de6edfc1f6afe736a2894a02fb0e7199dc72e00a6457060c9b3d78888453e8b66196513ef6c13b3e71406c8d4a92793e93bcd808f9c8e89fd4c03e6165
  internal-worker-address: ~
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/0.0.0.0/tcp/33065/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/0.0.0.0/tcp/35811/http
    network_admin_server:
      primary_network_admin_server_port: 45211
      worker_network_admin_server_base_port: 41793
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "0.0.0.0:39345"
  external-address: /ip4/0.0.0.0/udp/39345
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
