---
protocol-key-pair: a66jo0G/ngPz1lhTgwhHNK+Lt3kAeL72ry+BmY43MpCjuG5bTeqOWgRrfaWRpVgAhwhvzwA4hsPWhbmYeIrItpN23AX2MGNVBogETUmTUEoUSKogaircv3mwL6P/8z0vFFRTf8ck93oRbSVWfQuFBtlfGcveaxb14Qco/nzFlqo=
worker-key-pair: Ew6SMFNQKP77inRiI1YgX63uRVJJHzNnCI0RKORrLZmoA3mlnTiLhuu52V/iA3UA2mG0YzFcfWhAL7+kELViRg==
account-key-pair: ANMRokw2rY1kLehgboKhqxEGt5M0xT2mxMOiaicBDo313jHlyq9nRrSZbiaqLR2yE2VsrAyahTc7KeHirRaa61M=
network-key-pair: X6jkmTRHlQoJM8qJGAEASypFpu1bWP5DpBg5Wuqaekk/VGS67ysjQejaqFkVq3xOGkPsKhKHQan6vNK0qxRdiQ==
db-path: /root/.sui/sui_config/authorities_db/a3b86e5b4dea8e5a046b7da591a5580087086fcf003886c3d685b998788ac8b69376dc05f63063550688044d4993504a1448aa206a2adcbf79b02fa3fff33d2f1454537fc724f77a116d25567d0b8506d95f19cbde6b16f5e10728fe7cc596aa
network-address: /ip4/127.0.0.1/tcp/40555/http
json-rpc-address: "127.0.0.1:43597"
websocket-address: ~
metrics-address: "127.0.0.1:38049"
admin-interface-port: 42959
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/34007/http
  consensus-db-path: /root/.sui/sui_config/consensus_db/a3b86e5b4dea8e5a046b7da591a5580087086fcf003886c3d685b998788ac8b69376dc05f63063550688044d4993504a1448aa206a2adcbf79b02fa3fff33d2f1454537fc724f77a116d25567d0b8506d95f19cbde6b16f5e10728fe7cc596aa
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/42725/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/37855/http
    network_admin_server:
      primary_network_admin_server_port: 46229
      worker_network_admin_server_base_port: 35341
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:44377"
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
