---
protocol-key-pair: VxRragkkhdR5pPcsI37VgDE7mk6rXMIX9+5Z0PNTdCaXdrVZRGsMeOh1A8J14wfnbBe9UXYJNlw9ji09wKkM3/kK89DRQ8Xyamb+y9JhEcEMEN6ZrtPRgj0R+rQJ94odr0iZ72Z0xvTgPBlm5ZoInZnG7lkAYcXDyGjD65VA+GM=
worker-key-pair: sM01Gcv6DLnak/F+6WHNWzaPAkVnkcuWWmBEBW5NDQ3mC7qYQOdlLhEc5Yn+B0jnqQfoh5FCOhQV93pwM2Qrkw==
account-key-pair: API1Hp16/NTvyQA1SpjKYxua8/0i/hqGfFb5JqW6Opy4E+t38qjbdp3a2NR3mCT1aTsAXsNC25zbqXLlokBDM+w=
network-key-pair: 7M+MUoABO66UZP6p88+rxUj4OSVNmQXyjihHGL815yCC/ft7nKhLmVeg5Fpl0iVy6wjQmFwpcJj9pFs077tgwQ==
db-path: /root/.sui/sui_config/authorities_db/9776b559446b0c78e87503c275e307e76c17bd517609365c3d8e2d3dc0a90cdff90af3d0d143c5f26a66fecbd26111c10c10de99aed3d1823d11fab409f78a1daf4899ef6674c6f4e03c1966e59a089d99c6ee590061c5c3c868c3eb9540f863
network-address: /ip4/127.0.0.1/tcp/45689/http
json-rpc-address: "127.0.0.1:39285"
metrics-address: "127.0.0.1:42463"
admin-interface-port: 45341
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/46527/http
  consensus-db-path: /root/.sui/sui_config/consensus_db/9776b559446b0c78e87503c275e307e76c17bd517609365c3d8e2d3dc0a90cdff90af3d0d143c5f26a66fecbd26111c10c10de99aed3d1823d11fab409f78a1daf4899ef6674c6f4e03c1966e59a089d99c6ee590061c5c3c868c3eb9540f863
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/46077/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/38175/http
    network_admin_server:
      primary_network_admin_server_port: 34047
      worker_network_admin_server_base_port: 33327
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:43791"
  external-address: /ip4/127.0.0.1/udp/43791
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
