---
protocol-key-pair: HJZe4RD7IuGp3tzI6/Jj16ICrNEGGPTyYN44pY6W1iOFJgSw2LKZGrUJu+zhfzC3L2QecbucIXlT2E42sS1moYeAwFgH3vF/ikF0jcprWcsLyN+sSaG0nuT8DSeRqRXOuofKU6/ishHe+FSmzuhj3y78OHT7ggS3Q/iyIvnwZjM=
worker-key-pair: to4mL86yO5cz8mq9mIvRvON4yAi8slzJKJusyVVSg/SVzivfXOav7qzK4vPXLXD6ADTFCcHli9T0OzK+uyQOPw==
account-key-pair: AL2WBlXcczXOUBlFALNug2n1hID8cEHNTfvg25Nn5pw8kCK654oT3PdIffo5LRAmmxKS/iqOBbD39pEZJb1Zzog=
network-key-pair: iwrW2DKYqfRZRABYDoZE3w2SGoHui8Y51xnoQiz2OgAxSuksuzhSH4D4S17Gy8pEzmo+simFkiLAAoXg5Lk5ow==
db-path: /root/.sui/sui_config/authorities_db/852604b0d8b2991ab509bbece17f30b72f641e71bb9c217953d84e36b12d66a18780c05807def17f8a41748dca6b59cb0bc8dfac49a1b49ee4fc0d2791a915ceba87ca53afe2b211def854a6cee863df2efc3874fb8204b743f8b222f9f06633
network-address: /ip4/127.0.0.1/tcp/38477/http
json-rpc-address: "127.0.0.1:38633"
websocket-address: ~
metrics-address: "127.0.0.1:44833"
admin-interface-port: 34343
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/34065/http
  consensus-db-path: /root/.sui/sui_config/consensus_db/852604b0d8b2991ab509bbece17f30b72f641e71bb9c217953d84e36b12d66a18780c05807def17f8a41748dca6b59cb0bc8dfac49a1b49ee4fc0d2791a915ceba87ca53afe2b211def854a6cee863df2efc3874fb8204b743f8b222f9f06633
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/43031/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/35847/http
    network_admin_server:
      primary_network_admin_server_port: 46269
      worker_network_admin_server_base_port: 37605
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:35177"
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
