---
protocol-key-pair: RDEibRU1gd8HKNhD7iqApqe3w++JWNu7SDNDy63+qZiGiBxHPr5fPeQL6C2uv3y3HYNzalDlo+BjIvJvhc2q9DcR+c8EhvrdYMHyJpL4p1IOYhI8b9ZAUNf5LFrM2QIIwSICjVFYNbQ50F1r4KuN6Q+UGf/FemwLw7DZe5WdBJ8=
worker-key-pair: 02qXb//MKWx5Dy2jmAGUX2833vq3YXaBjCq9BQZksrRN7QAWbTrpwfUZks0yiRazlU0M7j+zKivkpc5HpmINmw==
account-key-pair: AAQbKdPLF8qFhmeS0Q0mGbvvqSzgCCkasxd1cuVpyyg5TfMiSQxD/6ZQpe5qpbuh9L+Tjvvrn6/tCAusSHuyo6k=
network-key-pair: jxoTjGSapvjkXI8WqiFExvq/jnfNYo2J4uVkdQxiLUZRU6jYC0dcsFxGuHt+DBQTI/jwXIgCh4h2IEBRZxhgOQ==
db-path: /root/.sui/sui_config/authorities_db/86881c473ebe5f3de40be82daebf7cb71d83736a50e5a3e06322f26f85cdaaf43711f9cf0486fadd60c1f22692f8a7520e62123c6fd64050d7f92c5accd90208c122028d515835b439d05d6be0ab8de90f9419ffc57a6c0bc3b0d97b959d049f
network-address: /ip4/127.0.0.1/tcp/35095/http
json-rpc-address: "127.0.0.1:36085"
metrics-address: "127.0.0.1:42403"
admin-interface-port: 34239
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/33007/http
  consensus-db-path: /root/.sui/sui_config/consensus_db/86881c473ebe5f3de40be82daebf7cb71d83736a50e5a3e06322f26f85cdaaf43711f9cf0486fadd60c1f22692f8a7520e62123c6fd64050d7f92c5accd90208c122028d515835b439d05d6be0ab8de90f9419ffc57a6c0bc3b0d97b959d049f
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/44915/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/45975/http
    network_admin_server:
      primary_network_admin_server_port: 43941
      worker_network_admin_server_base_port: 44239
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:36407"
  external-address: /ip4/127.0.0.1/udp/36407
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
