---
protocol-key-pair: BBRy00Dg2RF/vKSbBpniZ94KzHgXiLVKxoOXZoRZGy2F8l1t0v8oCqwDg2NgR/TlYl32TUJI8tPekTjargwpB2wadLmoT+lz26dnHDBXjrcLBtDZ/VPC3msz7YOsh0hMqH/EKWZ1rULCbBuRguRISydwMcANOc4u0KplHuYGvXA=
worker-key-pair: 8vPIQPePpoDA/QDW2vmFHFVMWAt7sH1cA6UPdjyVzizZDi5qE6sn03NVhztVr0CdCcHyDaUtYHI1AVTEykM/Ew==
account-key-pair: AP/IPj/AeJonWsXi69UBh68zdJkB+fKUaEtTwvR5IiBpdbGvtErjEVlWfUL33kTGwydeEiRNMezwunGyBcKHcpM=
network-key-pair: /6UR7DKj7p9Hy0MwdisMfNFzgk962w2V9EAcVKITffxFdEkGIIIeIWiQeIXAFeUez8CT5b8lRdHWk1OwOp7DZA==
db-path: /root/.sui/sui_config/authorities_db/85f25d6dd2ff280aac0383636047f4e5625df64d4248f2d3de9138daae0c29076c1a74b9a84fe973dba7671c30578eb70b06d0d9fd53c2de6b33ed83ac87484ca87fc4296675ad42c26c1b9182e4484b277031c00d39ce2ed0aa651ee606bd70
network-address: /ip4/127.0.0.1/tcp/34141/http
json-rpc-address: "127.0.0.1:35199"
metrics-address: "127.0.0.1:39247"
admin-interface-port: 36683
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/39283/http
  consensus-db-path: /root/.sui/sui_config/consensus_db/85f25d6dd2ff280aac0383636047f4e5625df64d4248f2d3de9138daae0c29076c1a74b9a84fe973dba7671c30578eb70b06d0d9fd53c2de6b33ed83ac87484ca87fc4296675ad42c26c1b9182e4484b277031c00d39ce2ed0aa651ee606bd70
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/46013/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/35383/http
    network_admin_server:
      primary_network_admin_server_port: 34757
      worker_network_admin_server_base_port: 44077
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:37069"
  external-address: /ip4/127.0.0.1/udp/37069
genesis:
  genesis-file-location: /root/.sui/sui_config/genesis.blob
